services:
  # ---------------------------------------------------------------------------
  # Identity Service
  # ---------------------------------------------------------------------------
  identity-service:
    image: micromart/identity-service
    container_name: micromart-identity-service
    build:
      context: ./identity-service
      dockerfile: Dockerfile

    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
      ACCESS_TOKEN_SECURITY_KEY: ${ACCESS_TOKEN_SECURITY_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME_IDENTITY: ${DATABASE_NAME_IDENTITY}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      COOKIE_SECURE: ${COOKIE_SECURE}
      HTTP_ONLY: ${HTTP_ONLY}

    networks:
      - micromart-network

# -----------------------------------------------------------------------------
# Networks and Volumes
# -----------------------------------------------------------------------------
networks:
  micromart-network:
    driver: bridge
