services:

  # ---------------------------------------------------------------------------
  # Discovery Service (Eureka Server)
  # ---------------------------------------------------------------------------
  discovery-service:
    image: micromart/discovery-service
    container_name: micromart-discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile

# FOR PUBLIC DEPLOY NEEDED TO MOVE FROM LOCAL TO SERVICE-NAME
#    environment:
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
#   ALSO POSRT SHOULD BE REMOVED IF YOU WANT AN ISOLATED DOCKER INTERNAL NETWORK
    ports:
      - "8761:8761"

    networks:
      - micromart-network

# -----------------------------------------------------------------------------
# Networks and Volumes
# -----------------------------------------------------------------------------
networks:
  micromart-network:
    driver: bridge

