services:
  # ---------------------------------------------------------------------------
  # Identity Service
  # ---------------------------------------------------------------------------
  gateway-service:
    image: micromart/identity-service
    container_name: micromart-identity-service
    build:
      context: ./identity-service
      dockerfile: Dockerfile

    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
      ACCESS_TOKEN_SECURITY_KEY: ${ACCESS_TOKEN_SECURITY_KEY}

    networks:
      - micromart-network

# -----------------------------------------------------------------------------
# Networks and Volumes
# -----------------------------------------------------------------------------
networks:
  micromart-network:
    driver: bridge
