-- ==========================================================
-- MicroMart Identity Service - Migration V3
-- 1. Create refresh_tokens table
-- 2. Create indexes & foreign keys
-- 3. Fix soft-delete unique constraints on users table
-- ==========================================================

-- Step 1: Create refresh_tokens table
CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                user_id UUID NOT NULL,
                                hashed_token VARCHAR(512) NOT NULL,
                                device_name VARCHAR(256) NOT NULL,
                                device_id UUID NOT NULL,
                                expiration_at TIMESTAMPTZ NOT NULL,
                                revoked BOOLEAN NOT NULL DEFAULT FALSE,
                                revoked_at TIMESTAMPTZ,
                                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_refresh_tokens_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users (id)
                                        ON DELETE CASCADE
);

-- Step 2: Indexes for refresh_tokens performance
-- Unique constraint/index on hashed_token for rapid token lookups
CREATE UNIQUE INDEX uq_refresh_tokens_hashed_token
    ON refresh_tokens (hashed_token);

-- Index for fetching all user tokens (e.g. revoke all devices, logout)
CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);

-- Composite partial index for finding active/valid tokens quickly
CREATE INDEX idx_refresh_tokens_active
    ON refresh_tokens (user_id, device_id)
    WHERE revoked = FALSE;


-- ==========================================================
-- Step 3: Fix Soft-Delete Unique Constraints on Users
-- ==========================================================

-- Drop PostgreSQL default unique constraints generated by V1
-- (PostgreSQL automatically names them table_column_key)
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_username_key;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;

-- Drop the old non-unique partial indexes from V1
DROP INDEX IF EXISTS idx_users_username_active;
DROP INDEX IF EXISTS idx_users_email_active;

-- Re-create them as UNIQUE Partial Indexes
-- This guarantees uniqueness strictly among ACTIVE accounts!
CREATE UNIQUE INDEX uq_users_username_active
    ON users (username)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_users_email_active
    ON users (email)
    WHERE deleted_at IS NULL;
